name: Fetch WG Device Management Issues & Add to Project

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  fetch-and-add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch WG Device Management Issues and PRs and Add to Project
        id: fetch-wg-device-management-items
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const projectId = "PVT_kwHOCAOYJ84AxfwF"; // Project Board ID

            async function fetchIssues(github) {
              const query = `repo:kubernetes/kubernetes is:open label:wg/device-management`;

              const items = [];
              let page = 1;
              let hasMore = true;

              while (hasMore) {
                const results = await github.rest.search.issuesAndPullRequests({
                  q: query,
                  per_page: 100,
                  page,
                });

                items.push(...results.data.items);
                hasMore = results.data.items.length === 100;
                page += 1;
              }

              return items;
            }

            async function addToProject(github, contentId) {
              try {
                await github.graphql(`
                  mutation($projectId: ID!, $contentId: ID!) {
                    addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                      item {
                        id
                      }
                    }
                  }
                `, {
                  projectId: projectId,
                  contentId: contentId
                });
                console.log(`Successfully added item ${contentId} to project.`);
              } catch (error) {
                console.error(`Failed to add item ${contentId} to project: ${error.message}`);
              }
            }

            console.log("Fetching all open WG Device Management issues and PRs from kubernetes/kubernetes...");
            const wgItems = await fetchIssues(github);

            if (wgItems.length === 0) {
              console.log("No open issues or PRs found with label wg/device-management.");
              return;
            }

            console.log(`Found ${wgItems.length} items. Adding to project...`);

            for (const item of wgItems) {
              await addToProject(github, item.node_id);
            }
